# Generated by Django 4.1.2 on 2022-12-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_author_book_is_bestelling_alter_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestelling',
            new_name='is_bestselling',
        ),
    ]
